export const productsData = [
    {
        id: 1,
        name: "Motherboard01",
        description: "Mother azul",
        price: 10000,
        pictureUrl: "",
        stock: "10",
        category: "motherboards",
    },
    {
        id: 2,
        name: "Motherboard02",
        description: "Mother rojo",
        price: 10000,
        pictureUrl: "",
        stock: "10",
        category: "motherboards",
    },
    {
        id: 3,
        name: "Motherboard03",
        description: "Mother verde",
        price: 11000,
        pictureUrl: "",
        stock: "8",
        category: "motherboards",
    },
    {
        id: 4,
        name: "Motherboard04",
        description: "Mother amarillo",
        price: 12000,
        pictureUrl: "",
        stock: "7",
        category: "motherboards",
    },
    {
        id: 5,
        name: "Procesador01",
        description: "procesador - Plateado",
        price: 15000,
        pictureUrl: "",
        stock: "15",
        category: "procesadores",
    },
    {
        id: 6,
        name: "Procesador02",
        description: "Procesador - Negro",
        price: 16000,
        pictureUrl: "",
        stock: "12",
        category: "procesadores",
    },
    {
        id: 7,
        name: "Procesador03",
        description: "Procesador Dorado",
        price: 18000,
        pictureUrl: "",
        stock: "9",
        category: "procesadores",
    },
    {
        id: 8,
        name: "Procesador04",
        description: "Procesador Rojo",
        price: 17000,
        pictureUrl: "",
        stock: "11",
        category: "procesadores",
    },
    {
        id: 9,
        name: "PlacaDeVideo01",
        description: "Azul",
        price: 25000,
        pictureUrl: "",
        stock: "6",
        category: "placasdevideo",
    },
    {
        id: 10,
        name: "PlacaDeVideo02",
        description: "Verde",
        price: 26000,
        pictureUrl: "",
        stock: "5",
        category: "placasdevideo",
    },
    {
        id: 11,
        name: "PlacaDeVideo03",
        description: "Plateado",
        price: 28000,
        pictureUrl: "",
        stock: "4",
        category: "placasdevideo",
    },
    {
        id: 12,
        name: "PlacaDeVideo04",
        description: "Negro",
        price: 27000,
        pictureUrl: "",
        stock: "7",
        category: "placasdevideo",
    }
]